# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _inverter_wrapper
else:
    import _inverter_wrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _inverter_wrapper.delete_SwigPyIterator

    def value(self):
        return _inverter_wrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _inverter_wrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _inverter_wrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _inverter_wrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _inverter_wrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _inverter_wrapper.SwigPyIterator_copy(self)

    def next(self):
        return _inverter_wrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _inverter_wrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _inverter_wrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _inverter_wrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _inverter_wrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _inverter_wrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _inverter_wrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _inverter_wrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _inverter_wrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _inverter_wrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _inverter_wrapper:
_inverter_wrapper.SwigPyIterator_swigregister(SwigPyIterator)

class vectorMatrixXd(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _inverter_wrapper.vectorMatrixXd_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _inverter_wrapper.vectorMatrixXd___nonzero__(self)

    def __bool__(self):
        return _inverter_wrapper.vectorMatrixXd___bool__(self)

    def __len__(self):
        return _inverter_wrapper.vectorMatrixXd___len__(self)

    def __getslice__(self, i, j):
        return _inverter_wrapper.vectorMatrixXd___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _inverter_wrapper.vectorMatrixXd___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _inverter_wrapper.vectorMatrixXd___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _inverter_wrapper.vectorMatrixXd___delitem__(self, *args)

    def __getitem__(self, *args):
        return _inverter_wrapper.vectorMatrixXd___getitem__(self, *args)

    def __setitem__(self, *args):
        return _inverter_wrapper.vectorMatrixXd___setitem__(self, *args)

    def pop(self):
        return _inverter_wrapper.vectorMatrixXd_pop(self)

    def append(self, x):
        return _inverter_wrapper.vectorMatrixXd_append(self, x)

    def empty(self):
        return _inverter_wrapper.vectorMatrixXd_empty(self)

    def size(self):
        return _inverter_wrapper.vectorMatrixXd_size(self)

    def swap(self, v):
        return _inverter_wrapper.vectorMatrixXd_swap(self, v)

    def begin(self):
        return _inverter_wrapper.vectorMatrixXd_begin(self)

    def end(self):
        return _inverter_wrapper.vectorMatrixXd_end(self)

    def rbegin(self):
        return _inverter_wrapper.vectorMatrixXd_rbegin(self)

    def rend(self):
        return _inverter_wrapper.vectorMatrixXd_rend(self)

    def clear(self):
        return _inverter_wrapper.vectorMatrixXd_clear(self)

    def get_allocator(self):
        return _inverter_wrapper.vectorMatrixXd_get_allocator(self)

    def pop_back(self):
        return _inverter_wrapper.vectorMatrixXd_pop_back(self)

    def erase(self, *args):
        return _inverter_wrapper.vectorMatrixXd_erase(self, *args)

    def __init__(self, *args):
        _inverter_wrapper.vectorMatrixXd_swiginit(self, _inverter_wrapper.new_vectorMatrixXd(*args))

    def push_back(self, x):
        return _inverter_wrapper.vectorMatrixXd_push_back(self, x)

    def front(self):
        return _inverter_wrapper.vectorMatrixXd_front(self)

    def back(self):
        return _inverter_wrapper.vectorMatrixXd_back(self)

    def assign(self, n, x):
        return _inverter_wrapper.vectorMatrixXd_assign(self, n, x)

    def resize(self, *args):
        return _inverter_wrapper.vectorMatrixXd_resize(self, *args)

    def insert(self, *args):
        return _inverter_wrapper.vectorMatrixXd_insert(self, *args)

    def reserve(self, n):
        return _inverter_wrapper.vectorMatrixXd_reserve(self, n)

    def capacity(self):
        return _inverter_wrapper.vectorMatrixXd_capacity(self)
    __swig_destroy__ = _inverter_wrapper.delete_vectorMatrixXd

# Register vectorMatrixXd in _inverter_wrapper:
_inverter_wrapper.vectorMatrixXd_swigregister(vectorMatrixXd)

class vectorVectorXd(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _inverter_wrapper.vectorVectorXd_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _inverter_wrapper.vectorVectorXd___nonzero__(self)

    def __bool__(self):
        return _inverter_wrapper.vectorVectorXd___bool__(self)

    def __len__(self):
        return _inverter_wrapper.vectorVectorXd___len__(self)

    def __getslice__(self, i, j):
        return _inverter_wrapper.vectorVectorXd___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _inverter_wrapper.vectorVectorXd___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _inverter_wrapper.vectorVectorXd___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _inverter_wrapper.vectorVectorXd___delitem__(self, *args)

    def __getitem__(self, *args):
        return _inverter_wrapper.vectorVectorXd___getitem__(self, *args)

    def __setitem__(self, *args):
        return _inverter_wrapper.vectorVectorXd___setitem__(self, *args)

    def pop(self):
        return _inverter_wrapper.vectorVectorXd_pop(self)

    def append(self, x):
        return _inverter_wrapper.vectorVectorXd_append(self, x)

    def empty(self):
        return _inverter_wrapper.vectorVectorXd_empty(self)

    def size(self):
        return _inverter_wrapper.vectorVectorXd_size(self)

    def swap(self, v):
        return _inverter_wrapper.vectorVectorXd_swap(self, v)

    def begin(self):
        return _inverter_wrapper.vectorVectorXd_begin(self)

    def end(self):
        return _inverter_wrapper.vectorVectorXd_end(self)

    def rbegin(self):
        return _inverter_wrapper.vectorVectorXd_rbegin(self)

    def rend(self):
        return _inverter_wrapper.vectorVectorXd_rend(self)

    def clear(self):
        return _inverter_wrapper.vectorVectorXd_clear(self)

    def get_allocator(self):
        return _inverter_wrapper.vectorVectorXd_get_allocator(self)

    def pop_back(self):
        return _inverter_wrapper.vectorVectorXd_pop_back(self)

    def erase(self, *args):
        return _inverter_wrapper.vectorVectorXd_erase(self, *args)

    def __init__(self, *args):
        _inverter_wrapper.vectorVectorXd_swiginit(self, _inverter_wrapper.new_vectorVectorXd(*args))

    def push_back(self, x):
        return _inverter_wrapper.vectorVectorXd_push_back(self, x)

    def front(self):
        return _inverter_wrapper.vectorVectorXd_front(self)

    def back(self):
        return _inverter_wrapper.vectorVectorXd_back(self)

    def assign(self, n, x):
        return _inverter_wrapper.vectorVectorXd_assign(self, n, x)

    def resize(self, *args):
        return _inverter_wrapper.vectorVectorXd_resize(self, *args)

    def insert(self, *args):
        return _inverter_wrapper.vectorVectorXd_insert(self, *args)

    def reserve(self, n):
        return _inverter_wrapper.vectorVectorXd_reserve(self, n)

    def capacity(self):
        return _inverter_wrapper.vectorVectorXd_capacity(self)
    __swig_destroy__ = _inverter_wrapper.delete_vectorVectorXd

# Register vectorVectorXd in _inverter_wrapper:
_inverter_wrapper.vectorVectorXd_swigregister(vectorVectorXd)

class Inverter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _inverter_wrapper.Inverter_swiginit(self, _inverter_wrapper.new_Inverter())

    def getInverse(self, *args):
        return _inverter_wrapper.Inverter_getInverse(self, *args)

    def getInverseRef(self, M):
        return _inverter_wrapper.Inverter_getInverseRef(self, M)

    def getInverseList(self, matrices):
        return _inverter_wrapper.Inverter_getInverseList(self, matrices)
    __swig_destroy__ = _inverter_wrapper.delete_Inverter

# Register Inverter in _inverter_wrapper:
_inverter_wrapper.Inverter_swigregister(Inverter)


def templatedInverse_d(M):
    return _inverter_wrapper.templatedInverse_d(M)

from .extensions import Inverter_getInversePlus1
Inverter.getInversePlus1 = Inverter_getInversePlus1



